# -*- coding: utf-8 -*-
"""Data Vizualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JzysfXUQ_4eCca1Kdw6mTikAgV8SaSrw

## Import Library
"""

import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns

"""## Import Dataset"""

df = pd.read_csv('/content/BankChurners.csv')
df.head()

"""## PreProcessing Data"""

df.describe()

df.info()

df.columns

df.columns = df.columns.str.lower()
df.columns

df_filtered = df[['attrition_flag', 'customer_age', 'gender', 'education_level', 'income_category']]
df_filtered.head(15)

df_filtered.info()

"""## Data Visualization

## 1. [50 poin] Buatlah 5 visualisasi untuk kolom attrition_flag, customer_age, gender,education_level, dan income_category. Satu kolom satu visualisasi saja. Wajib ada pie chart, donut chart, vertical bar chart, dan horizontal bar chart (pilih salah satu untuk suatu kolom).

Pie Chart untuk Attrition_Flag
"""

plt.figure(figsize=(6, 6))
attrition_counts = df_filtered['attrition_flag'].value_counts()
plt.pie(attrition_counts, labels=attrition_counts.index, autopct='%1.1f%%', startangle=90, colors=['lightblue', 'lightcoral'])
plt.title('Customer Attrition Distribution')
plt.show()

""" Donut Chart untuk Gender"""

plt.figure(figsize=(6, 6))
gender_counts = df_filtered['gender'].value_counts()
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=90, colors=['pink', 'skyblue'], wedgeprops=dict(width=0.3))
plt.title('Gender Distribution')
plt.show()

"""Vertical Bar Chart untuk Customer_Age"""

plt.figure(figsize=(10, 6))
age_counts = df_filtered['customer_age'].value_counts().sort_index()
plt.bar(age_counts.index, age_counts.values, color='purple')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""Horizontal Bar Chart untuk Education_Level"""

plt.figure(figsize=(10, 6))
education_counts = df_filtered['education_level'].value_counts()
plt.barh(education_counts.index, education_counts.values, color='orange')
plt.title('Education Level Distribution')
plt.xlabel('Count')
plt.ylabel('Education Level')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

"""Bar Chart untuk Income_Category"""

plt.figure(figsize=(10, 6))
income_counts = df_filtered['income_category'].value_counts()
plt.bar(income_counts.index, income_counts.values, color='green')
plt.title('Income Category Distribution')
plt.xlabel('Income Category')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""## 2. [5 poin] Tuliskan informasi/insight dari setiap visualisasi yang dibuat untuk No. 1.

# Pie Chart untuk Attrition_Flag

Proporsi Pelanggan Aktif vs Churn:

83.9% pelanggan adalah Existing Customers, artinya mereka masih aktif menggunakan layanan.
16.1% pelanggan adalah Attrited Customers, yaitu pelanggan yang berhenti atau churn.

Interpretasi:

Meskipun mayoritas pelanggan masih aktif, churn rate sebesar 16.1% cukup signifikan dan memerlukan perhatian khusus.
Perusahaan harus melakukan analisis mendalam untuk memahami alasan pelanggan churn (misalnya, terkait layanan, harga, atau produk) dan mengambil langkah-langkah untuk meningkatkan retensi pelanggan.

#Donut Chart untuk Gender

Distribusi Gender:

Pelanggan dengan jenis kelamin Perempuan (F) mendominasi dengan proporsi 52.9%.
Pelanggan dengan jenis kelamin Laki-laki (M) memiliki proporsi 47.1%.

Interpretasi:

Distribusi ini relatif seimbang antara pria dan wanita, meskipun wanita sedikit lebih banyak.
Perusahaan dapat mempertimbangkan pendekatan pemasaran yang inklusif untuk kedua gender, tetapi bisa juga memberikan fokus lebih pada kebutuhan atau preferensi pelanggan perempuan, mengingat mereka adalah mayoritas.

# Vertical Bar Chart untuk Customer_Age

Kelompok Usia Dominan:

Pelanggan usia 43 dan 49 mendominasi populasi pelanggan.
Ini menunjukkan bahwa pelanggan di usia paruh baya (43-50 tahun) menjadi segmen terbesar dalam basis pelanggan.

Kelompok usia 43 sampai 50 cenderung berada pada tahap kehidupan yang stabil secara finansial, produktif dalam pekerjaan, dan memiliki daya beli yang cukup tinggi.

# Horizontal Bar Chart untuk Education_Level

Mayoritas Pelanggan:

Tingkat pendidikan Graduate (sarjana) mendominasi. Ini menunjukkan bahwa sebagian besar pelanggan memiliki tingkat pendidikan yang cukup tinggi dan Pelanggan dengan tingkat pendidikan Graduate kemungkinan memiliki kemampuan pemahaman yang baik terhadap konsep produk/layanan yang lebih kompleks.

Pelanggan dengan pendidikan Doctorate mungkin lebih tertarik pada produk dengan konsep sederhana dan mudah dipahami.

# Bar Chart untuk Income_Category

Distribusi pelanggan berdasarkan kategori pendapatan membantu memahami daya beli pelanggan. Income category pada Less than $40K lebih mendominasi berarti  perusahaan dapat menawarkan produk dengan harga yang lebih kompetitif. Pendapatan Tinggi $120K merupakan kelompok pelanggan dengan jumlah yang sangat kecil dibandingkan kelompok pendapatan lainnya. Hal ini menunjukkan bahwa perusahaan saat ini tidak banyak menarik atau mempertahankan pelanggan dari segmen pendapatan tinggi.

## 3.  Buatlah 1 visualisasi menggunakan countplot yang memadukan lebih dari satu kolom (bebas antar kolom yang mana saja)
"""

df.columns

plt.figure(figsize=(8, 6))
sns.countplot(x='education_level', hue='gender', data=df_filtered, hue_order=['M', 'F'])
plt.title('Jumlah Pelanggan Churn Berdasarkan Pendidikan dan Gender')
plt.xlabel('Tingkat Pendidikan')
plt.ylabel('Jumlah Pelanggan')
plt.show()

"""Insight :

Pelanggan perempuan cenderung lebih rentan mengalami churn dibandingkan laki-laki di semua tingkatan pendidikan, dengan mayoritas churn berasal dari kelompok berpendidikan 'Graduate,' sementara pelanggan dengan tingkat pendidikan 'Doctorate' menunjukkan loyalitas tertinggi dengan churn paling rendah.

## 4) Buatlah 1 visualisasi menggunakan scatterplot yang memadukan lebih dari satu kolom (bebas antar kolom yang mana saja)
"""

plt.figure(figsize=(8, 6))
sns.scatterplot(x='customer_age', y='income_category', hue='gender', data=df_filtered)
plt.title('Hubungan Antara Usia dan Kategori Pendapatan Berdasarkan Gender')
plt.xlabel('Usia Pelanggan')
plt.ylabel('Kategori Pendapatan')
plt.show()

"""Insight =

Distribusi Gender:

Mayoritas laki-laki (ditandai dengan titik biru) berada pada kategori pendapatan $60K - $80K, $80K - $120K, dan $120K+.
Mayoritas perempuan (ditandai dengan titik oranye) berada pada kategori pendapatan "Less than $40K" dan "Unknown".

Distribusi Pendapatan:
Sangat sedikit individu yang berada di kategori pendapatan $40K - $60K.

##5) Buatlah 1 visualisasi menggunakan heatmap yang memadukan lebih dari satu kolom (bebas antar kolom yang mana saja)
"""

numeric_cols = ['customer_age', 'credit_limit', 'total_trans_amt', 'avg_utilization_ratio']
correlation_matrix = df[numeric_cols].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", cbar=True)
plt.title('Heatmap Korelasi Antar Kolom Numerik', fontsize=14)
plt.show()

"""Insight =

Korelasi Positif:

credit_limit dan total_trans_amt memiliki korelasi positif yang lemah (0.17). Ini menunjukkan bahwa pelanggan dengan limit kredit yang lebih tinggi cenderung melakukan transaksi dengan jumlah yang lebih tinggi.

Korelasi Negatif:

credit_limit dan avg_utilization_ratio memiliki korelasi negatif yang cukup kuat (-0.48). Ini menunjukkan bahwa pelanggan dengan limit kredit yang lebih tinggi cenderung menggunakan persentase kecil dari limit kredit mereka.

Korelasi Lemah:

Korelasi lainnya sangat lemah (0.00 - 0.05), yang menunjukkan tidak ada hubungan yang signifikan antara kolom-kolom tersebut.
"""